# Generated by Django 4.0.2 on 2022-02-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List_Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المهمه')),
                ('time_mission', models.TimeField(verbose_name='وقت المهمه')),
                ('day_mission', models.DateField(verbose_name='يوم المهمه')),
                ('finish_mission', models.BooleanField(default=False, verbose_name='انتهاء المهمه')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
