# Generated by Django 4.0.2 on 2022-02-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('do_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_mission',
            name='finish_mission',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='انتهاء المهمه'),
        ),
    ]
