# Generated by Django 4.0.2 on 2022-02-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('do_list', '0002_alter_list_mission_finish_mission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_mission',
            name='finish_mission',
            field=models.BooleanField(blank=True, null=True, verbose_name='انتهاء المهمه'),
        ),
    ]
